<!DOCTYPE HTML>
<html lang="en-US">
<head>
	<meta charset="UTF-8">
	<title>This is Title</title>
</head>
<body>

<h1>University of Bangladesh</h1><a name="first"></a>
	<p><b>Organization</b></p><!-- This is 1st content --> 
	<a href="#middle">Middle content</a> <br />
	<a href="#last">Last content</a>
	
	<p>This is pragraph no 01. This is pragraph no 01. This is pragraph no 01. This is pragraph no 01. This is pragraph no 01. This is pragraph no 01. This is pragraph no 01. This is pragraph no 01.This is pragraph no 01. This is pragraph no 01. This is pragraph no 01. This is pragraph no 01.This is pragraph no 01. This is pragraph no 01. This is pragraph no 01. This is pragraph no 01. </p>
	
	<p>One Two three four five six seven eight nine ten. One Two three four five six seven eight nine ten. One Two three four five six seven eight nine ten. One Two three four five six seven eight nine ten. One Two three four five six seven eight nine ten. One Two three four five six seven eight nine ten. One Two three four five six seven eight nine ten. One Two three four five six seven eight nine ten. One Two three four five six seven eight nine ten.</p>
	<a name="middle">Middle Content</a>
	<a href="#last">Last content</a>
	<p>This is pragraph no 02. This is pragraph no 02. This is pragraph no 02. This is pragraph no 02. This is pragraph no 02. This is pragraph no 02. This is pragraph no 02. This is pragraph no 02. This is pragraph no 02. This is pragraph no 02. This is pragraph no 02. This is pragraph no 02. This is pragraph no 02. This is pragraph no 02. This is pragraph no 02. This is pragraph no 02. This is pragraph no 02. This is pragraph no 02. This is pragraph no 02. This is pragraph no 02. This is pragraph no 02. This is pragraph no 02. This is pragraph no 02. This is pragraph no 02. This is pragraph no 02. This is pragraph no 02. This is pragraph no 02. This is pragraph no 02. This is pragraph no 02. This is pragraph no 02.</p><!--This is middle content -->
	
	<p>This is pragraph. This is pragraph. This is pragraph. This is pragraph. This is pragraph. This is pragraph.This is pragraph. This is pragraph.This is pragraph. This is pragraph. This is pragraph. This is pragraph. This is pragraph. This is pragraph. This is pragraph. This is pragraph. This is pragraph. This is pragraph. This is pragraph. This is pragraph. This is pragraph. This is pragraph. This is pragraph. This is pragraph. This is pragraph. This is pragraph. This is pragraph. This is pragraph. This is pragraph. This is pragraph. This is pragraph. This is pragraph. This is pragraph. This is pragraph. This is pragraph. This is pragraph. This is pragraph.</p>
	<p>Bangladesh, east of India on the Bay of Bengal, is South Asian country of lush greenery and many waterways. Its Padma (Ganges), Meghna and Jamuna rivers create fertile alluvial plains, and travel by boat is common. On the southern coast, the Sundarbans, an enormous mangrove forest shared with India, are home to the Royal Bengal tiger. Bangladesh, east of India on the Bay of Bengal, is South Asian country of lush greenery and many waterways. Its Padma (Ganges), Meghna and Jamuna rivers create fertile alluvial plains, and travel by boat is common. On the southern coast, the Sundarbans, an enormous mangrove forest shared with India, are home to the Royal Bengal tiger. Bangladesh, east of India on the Bay of Bengal, is South Asian country of lush greenery and many waterways. Its Padma (Ganges), Meghna and Jamuna rivers create fertile alluvial plains, and travel by boat is common. On the southern coast, the Sundarbans, an enormous mangrove forest shared with India, are home to the Royal Bengal tiger. Bangladesh, east of India on the Bay of Bengal, is South Asian country of lush greenery and many waterways. Its Padma (Ganges), Meghna and Jamuna rivers create fertile alluvial plains, and travel by boat is common. On the southern coast, the Sundarbans, an enormous mangrove forest shared with India, are home to the Royal Bengal tiger. Bangladesh, east of India on the Bay of Bengal, is South Asian country of lush greenery and many waterways. Its Padma (Ganges), Meghna and Jamuna rivers create fertile alluvial plains, and travel by boat is common. On the southern coast, the Sundarbans, an enormous mangrove forest shared with India, are home to the Royal Bengal tiger. Bangladesh, east of India on the Bay of Bengal, is South Asian country of lush greenery and many waterways. Its Padma (Ganges), Meghna and Jamuna rivers create fertile alluvial plains, and travel by boat is common. On the southern coast, the Sundarbans, an enormous mangrove forest shared with India, are home to the Royal Bengal tiger. Bangladesh, east of India on the Bay of Bengal, is South Asian country of lush greenery and many waterways. Its Padma (Ganges), Meghna and Jamuna rivers create fertile alluvial plains, and travel by boat is common. On the southern coast, the Sundarbans, an enormous mangrove forest shared with India, are home to the Royal Bengal tiger.</p>
	<p>This is pragraph. This is pragraph. This is pragraph. This is pragraph. This is pragraph. This is pragraph.This is pragraph. This is pragraph.This is pragraph. This is pragraph. This is pragraph. This is pragraph. This is pragraph. This is pragraph. This is pragraph. This is pragraph. This is pragraph. This is pragraph. This is pragraph. This is pragraph. This is pragraph. This is pragraph. This is pragraph. This is pragraph. This is pragraph. This is pragraph. This is pragraph. This is pragraph. This is pragraph. This is pragraph. This is pragraph. This is pragraph. This is pragraph. This is pragraph. This is pragraph. This is pragraph. This is pragraph.</p>
	
	<a name="last">last Content</a>
	
	<p>Bangladesh University is a for-profit, sectarian, private university located near the Jatiyo Sangshad Bhaban in Dhaka, Bangladesh. The university was established in 2001 under the Private University Act 1992. Bangladesh University is a for-profit, sectarian, private university located near the Jatiyo Sangshad Bhaban in Dhaka, Bangladesh. The university was established in 2001 under the Private University Act 1992. Bangladesh University is a for-profit, sectarian, private university located near the Jatiyo Sangshad Bhaban in Dhaka, Bangladesh. The university was established in 2001 under the Private University Act 1992. Bangladesh University is a for-profit, sectarian, private university located near the Jatiyo Sangshad Bhaban in Dhaka, Bangladesh. The university was established in 2001 under the Private University Act 1992. Bangladesh University is a for-profit, sectarian, private university located near the Jatiyo Sangshad Bhaban in Dhaka, Bangladesh. The university was established in 2001 under the Private University Act 1992.</p><!-- This is Last Content --> 
	<a href="#first">Go First content Chick here</a><br />
	
	
	<br />		<a href="E10HTML5&CSS3D08Feb17.php" target="_blank">Exercise10ClichHere</a>
		
</body>
</html>